spring:
  datasource:
    username: root
    password: warrior_520
    url: jdbc:mysql://192.168.57.131:3306/jdbc
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 30000
        validation-query: select 1 from dual
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        #配置监控统计拦截的filters,去掉后监控页面sql无法统计，'wall'用于防火墙
        filter: stat,wall,log4j
        max-pool-prepared-statement-per-connection-size: 20
        use-global-data-source-stat: true
        connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500